# Example configuration for one camera
# Expected to be used with camera.launch.py using default name and namespace

/ifm3d/camera:
  ros__parameters:
    buffer_id_list:
      - AMPLITUDE_IMAGE
      - NORM_AMPLITUDE_IMAGE
      - CONFIDENCE_IMAGE
      - JPEG_IMAGE
      - RADIAL_DISTANCE_IMAGE
      - XYZ
      - EXTRINSIC_CALIB
    ip: 192.168.0.69
    pcic_port: 50010
    tf:
      cloud_link:
        frame_name: "camera_cloud_link"
      optical_link:
        frame_name: "camera_optical_link"
    use_sim_time: false
    xmlrpc_port: 80
